### 주민등록
POST /residents
Host: localhost:8080
Content-Type: application/json

{
  "name": "남길동",
  "residentRegistrationNumber" : "130914-1234561",
  "genderCode" : "남",
  "birthDate" : "1913-09-14T07:22:00",
  "birthPlaceCode" : "자택",
  "registrationBaseAddress" : "경기도 성남시 분당구 대왕판교로645번길",
  "deathDate" : "2021-04-29T09:03:00",
  "deathPlaceCode" : "주택",
  "deathPlaceAddress" : "강원도 고성군 금강산로 290번길"
}

### 주민등록 null
POST /residents
Host: localhost:8080
Content-Type: application/json

{
  "name": "남길동",
  "residentRegistrationNumber" : "130914-1234561",
  "genderCode" : "남",
  "birthDate" : "1913-09-14T07:22:00",
  "birthPlaceCode" : "자택",
  "registrationBaseAddress" : "경기도 성남시 분당구 대왕판교로645번길"
}

### 주민수정
PUT /residents/8
Host: localhost:8080
Content-Type: application/json

{
  "name": "남길순",
  "residentRegistrationNumber" : "130914-1234561",
  "genderCode" : "여",
  "birthDate" : "1913-09-14T07:22:00",
  "birthPlaceCode" : "병원",
  "registrationBaseAddress" : "경기도 성남시 분당구 대왕판교로645번길"
}

### 주민삭제
DELETE /residents/2
Host: localhost:8080
Content-Type: application/json

### 가족관계 등록
POST /residents/8/relationship
Host: localhost:8080
Content-Type: application/json

{
  "familySerialNumber": 9,
  "relationship": "부"
}

### 가족관계 수정
PUT /residents/8/relationship/9
Host: localhost:8080
Content-Type: application/json

{
  "relationship": "모"
}

### 가족관계 삭제
DELETE /residents/8/relationship/9
Host: localhost:8080
Content-Type: application/json

### 출생신고서 등록
POST /residents/8/birth
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber": 9,
  "birthDeathReportDate" : "2012-03-17",
  "birthReportQualificationsCode" : "부",
  "phoneNumber" : "010-1234-5678"
}

### 출생신고서 수정
PUT /residents/8/birth/9
Host: localhost:8080
Content-Type: application/json

{
  "birthDeathReportDate" : "2012-03-17",
  "birthReportQualificationsCode" : "모",
  "phoneNumber" : "010-1234-5678"
}

### 출생신고서 삭제
DELETE /residents/8/birth/9
Host: localhost:8080
Content-Type: application/json

### 사망신고서 등록
POST /residents/8/death
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber": 9,
  "birthDeathReportDate" : "2020-03-17",
  "deathReportQualificationsCode" : "비동거친족",
  "phoneNumber" : "010-1234-5678"
}

### 사망신고서 수정
PUT /residents/8/death/9
Host: localhost:8080
Content-Type: application/json

{
  "birthDeathReportDate" : "2020-03-17",
  "deathReportQualificationsCode" : "동거자",
  "phoneNumber" : "010-1234-5678"
}

### 사망신고서 삭제
DELETE /residents/8/death/9
Host: localhost:8080
Content-Type: application/json
